FROM python:3.9

# must be in base image
RUN pip install git+https://github.com/bitmakerla/estela-entrypoint.git
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY . /usr/src/app

RUN pip install --no-cache-dir -r requirements.txt
RUN mkdir /fifo-data
